CREATE DATABASE IF NOT EXISTS `trazabilidad+Antelo`;

-- Usar la base de datos
USE `trazabilidad+Antelo`;

-- Creacion de la tabla de cepas adquiridas
CREATE TABLE IF NOT EXISTS CEPAS (
    MOO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);
 
-- Creacion de tabla para firma de analista
 
 CREATE TABLE IF NOT EXISTS ANALISTA_FIRMA (
    ID_ANALISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

-- creacion de observaciones para registro de cepas de reserva
CREATE TABLE IF NOT EXISTS OBSERVACION_RESERVA (
    ID_OBSERVACION INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL UNIQUE
);

-- tabla para pruebas bioquimicas 
CREATE TABLE IF NOT EXISTS PRUEBAS_CEPAS (
	ID_PRUEBAS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TIPOS VARCHAR(200) NOT NULL UNIQUE
);

-- tabla para observaciones prearmadas  
CREATE TABLE IF NOT EXISTS OBSERVACION_TRABAJO (
	ID_OBSERVACIONTRABAJO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (200) NOT NULL UNIQUE
);

-- Tabla principal de stock
CREATE TABLE IF NOT EXISTS STOCK_CEPAS (
    ID_STOCK INT AUTO_INCREMENT PRIMARY KEY,   
    MOO_ID INT NOT NULL,                     
    NUMERACION INT NOT NULL,                    
    FECHA_RECEPCION DATE NOT NULL,
    FECHA_VTO DATE NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_PRUEBAS INT,
    RESULTADO VARCHAR(500),
    OBSERVACIONES VARCHAR(500),
    ID_ANALISTA INT,
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (MOO_ID) REFERENCES CEPAS(MOO_ID)
);

-- tabla para cepas de reserva
CREATE TABLE IF NOT EXISTS CEPA_RESERVA (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_STOCK INT NOT NULL,
    NUMERO_ALICUOTA VARCHAR(10) NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_OBSERVACION INT, 
    ID_ANALISTA INT,  
    
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACION) REFERENCES OBSERVACION_RESERVA(ID_OBSERVACION),
    FOREIGN KEY (ID_STOCK) REFERENCES STOCK_CEPAS(ID_STOCK)
);

-- tabla para cepas de trabajo 
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO (
    ID_TRABAJO INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL INT NOT NULL, 
    ID_RESERVA_ORIGEN INT, 
    ID_TRABAJO_ORIGEN INT, 
    FECHA_ACTIVACION DATE NOT NULL,
    ID_PRUEBAS INT,
    RESULTADO VARCHAR(500),
    ID_OBSERVACIONTRABAJO INT,
    ID_ANALISTA INT,
    FECHA_BAJA DATE,

    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_RESERVA_ORIGEN) REFERENCES CEPA_RESERVA(ID_RESERVA) ON DELETE CASCADE,
    FOREIGN KEY (ID_TRABAJO_ORIGEN) REFERENCES CEPA_TRABAJO(ID_TRABAJO) ON DELETE CASCADE

);

-- tabla STOCK de cultivos
CREATE TABLE IF NOT EXISTS MEDIO_CULTIVO_STOCK (
    ID_MEDIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    FABRICANTE VARCHAR(100),
    LOTE VARCHAR(50),
    VENCIMIENTO DATE
); 

-- tabla para control de los medios de cultivo
CREATE TABLE IF NOT EXISTS ECOMETRICO (
    ID_ECOMETRICO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    ICA INT NOT NULL,         
    ICE INT NOT NULL,         
    RESULTADO VARCHAR(100) NOT NULL
);

-- tabla para control de agua destilada usada en medios ed cultivos
CREATE TABLE IF NOT EXISTS AGUA_DEST (
    ID_AGUA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_ENTRADA DATE NOT NULL,
    CONTROL VARCHAR(100),
    ID_ANALISTA INT, 
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA)
);

-- tabla para registrar la preparacion de los medios usados
CREATE TABLE IF NOT EXISTS PREPARACION_MEDIO_CULTIVO (
    ID_PREPARACION INT AUTO_INCREMENT PRIMARY KEY,
    ID_MEDIO INT NOT NULL,           
    FECHA_PREPARACION DATE NOT NULL,
    ID_ECOMETRICO INT,               
    ID_AGUA INT,                      
    ID_ANALISTA INT,                  
    PH INT,                          
    OBSERVACIONES VARCHAR(500),

    FOREIGN KEY (ID_MEDIO) REFERENCES MEDIO_CULTIVO_STOCK(ID_MEDIO),
    FOREIGN KEY (ID_ECOMETRICO) REFERENCES ECOMETRICO(ID_ECOMETRICO),
    FOREIGN KEY (ID_AGUA) REFERENCES AGUA_DEST(ID_AGUA),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA)
);

ALTER TABLE CEPA_TRABAJO
    ADD COLUMN ID_PREPARACION INT NULL;

ALTER TABLE CEPA_TRABAJO
    ADD CONSTRAINT FK_CEPA_TRABAJO_PREPARACION
        FOREIGN KEY (ID_PREPARACION) REFERENCES PREPARACION_MEDIO_CULTIVO(ID_PREPARACION) ON DELETE SET NULL;

-- tabla para registrar los equipos usados
CREATE TABLE IF NOT EXISTS EQUIPOS (
    ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(100),
    FECHA_CALIBRACION DATE,
    VTO_CALIBRACION DATE
);

-- tabla para registrar el proceso de esterilizacion
CREATE TABLE IF NOT EXISTS ESTERILIZACION (
    ID_CICLO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,
    FECHA DATE NOT NULL,
    TIEMPO INT,              
    TEMPERATURA INT, 
    ID_ANALISTA INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA)
);

-- tabla para registrar los controles de calidad
CREATE TABLE IF NOT EXISTS AUTOCLAVE_VERIF (
    ID_AUTOCLAVE INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,          
    FECHA DATE NOT NULL,
    LECTURA_1 DECIMAL(8,3),
    LECTURA_2 DECIMAL(8,3),
    CUMPLE BOOLEAN,                   
    ID_ANALISTA INT,

    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA)
);

ALTER TABLE PREPARACION_MEDIO_CULTIVO
    ADD COLUMN ID_CICLO INT NULL;

ALTER TABLE PREPARACION_MEDIO_CULTIVO
    ADD CONSTRAINT FK_PREPARACION_CICLO
        FOREIGN KEY (ID_CICLO) REFERENCES ESTERILIZACION(ID_CICLO) ON DELETE SET NULL;