CREATE DATABASE IF NOT EXISTS `trazabilidad+Antelo`;

-- Usar la base de datos
USE `trazabilidad+Antelo`;

-- Creacion de la tabla de cepas adquiridas
CREATE TABLE IF NOT EXISTS CEPAS (
    MOO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);
 
-- Creacion de tabla para firma de analista
 
 CREATE TABLE IF NOT EXISTS ANALISTA_FIRMA (
    ID_ANALISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

-- creacion de observaciones para registro de cepas de reserva
CREATE TABLE IF NOT EXISTS OBSERVACION_RESERVA (
    ID_OBSERVACION INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL UNIQUE
);

-- tabla para pruebas bioquimicas 
CREATE TABLE IF NOT EXISTS PRUEBAS_CEPAS (
	ID_PRUEBAS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TIPOS VARCHAR(200) NOT NULL UNIQUE
);

-- tabla para observaciones prearmadas  
CREATE TABLE IF NOT EXISTS OBSERVACION_TRABAJO (
	ID_OBSERVACIONTRABAJO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (200) NOT NULL UNIQUE
);

-- Tabla principal de stock
CREATE TABLE IF NOT EXISTS STOCK_CEPAS (
    ID_STOCK INT AUTO_INCREMENT PRIMARY KEY,   
    MOO_ID INT NOT NULL,                     
    NUMERACION INT NOT NULL,                    
    FECHA_RECEPCION DATE NOT NULL,
    FECHA_VTO DATE NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_PRUEBAS INT,
    RESULTADO VARCHAR(500),
    OBSERVACIONES VARCHAR(500),
    ID_ANALISTA INT,
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (MOO_ID) REFERENCES CEPAS(MOO_ID)
);

-- tabla para cepas de reserva
CREATE TABLE IF NOT EXISTS CEPA_RESERVA (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_STOCK INT NOT NULL,
    NUMERO_ALICUOTA VARCHAR(10) NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_OBSERVACION INT, 
    ID_ANALISTA INT,  
    
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACION) REFERENCES OBSERVACION_RESERVA(ID_OBSERVACION),
    FOREIGN KEY (ID_STOCK) REFERENCES STOCK_CEPAS(ID_STOCK)
);

-- tabla para cepas de trabajo 
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO (
    ID_TRABAJO INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL INT NOT NULL, 
    ID_RESERVA_ORIGEN INT, 
    ID_TRABAJO_ORIGEN INT, 
    FECHA_ACTIVACION DATE NOT NULL,
    ID_PRUEBAS INT,
    RESULTADO VARCHAR(500),
    ID_OBSERVACIONTRABAJO INT,
    ID_ANALISTA INT,
    FECHA_BAJA DATE,

    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_RESERVA_ORIGEN) REFERENCES CEPA_RESERVA(ID_RESERVA) ON DELETE CASCADE,
    FOREIGN KEY (ID_TRABAJO_ORIGEN) REFERENCES CEPA_TRABAJO(ID_TRABAJO) ON DELETE CASCADE
);






