CREATE DATABASE IF NOT EXISTS `trazabilidad+Antelo`;

-- Usar la base de datos
USE `trazabilidad+Antelo`;

-- Creacion de la tabla de cepas adquiridas
CREATE TABLE IF NOT EXISTS CEPAS (
    MOO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);
 
-- Creacion de tabla para firma de analista
 
 CREATE TABLE IF NOT EXISTS ANALISTA_FIRMA (
    ID_ANALISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

-- creacion de observaciones para registro de cepas de reserva
CREATE TABLE IF NOT EXISTS OBSERVAC_RESERVA (
    ID_OBSERVACION INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL UNIQUE
);

-- tabla para pruebas bioquimicas 
CREATE TABLE IF NOT EXISTS PRUEBAS_CEPAS (
	ID_PRUEBAS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TIPOS VARCHAR(200) NOT NULL UNIQUE
);

-- tabla para observaciones prearmadas  
CREATE TABLE IF NOT EXISTS OVSERVACION_TRABAJO (
	ID_OBSERVACIONTRABAJO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (200) NOT NULL UNIQUE
);

RENAME TABLE OVSERVACION_TRABAJO TO OBSERVACION_TRABAJO;

-- Tabla principal de stock
CREATE TABLE IF NOT EXISTS STOCK_CEPAS (
    ID_STOCK VARCHAR(50) PRIMARY KEY NOT NULL,
    FECHA_RECEPCION DATE NOT NULL,
    FECHA_VTO DATE NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_PRUEBAS INT,
    RESULTADO TEXT,
    OBSERVACIONES TEXT,
    ID_ANALISTA INT,
    MOO_ID INT NOT NULL,

    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (MOO_ID) REFERENCES CEPAS(MOO_ID)
);

-- tabla para cepas de reserva
CREATE TABLE IF NOT EXISTS CEPA_RESERVA (
	ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_STOCK VARCHAR(50) NOT NULL,
    NUMERO_ALICUOTA VARCHAR (10) NOT NULL,
    FECHA_RECONSTITUCION DATE,
    ID_OBSERVACION INT, 
    ID_ANALISTA INT,  
    
    FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACION) REFERENCES OBSERVAC_RESERVA(ID_OBSERVACION),
    FOREIGN KEY (ID_STOCK) REFERENCES STOCK_CEPAS(ID_STOCK)
);

-- tabla para cepas de trabajo 2
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO2 (
ID_TRABAJO2 INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
ID_RESERVA INT,
FECHA_ACTIVACION DATE NOT NULL,
ID_PRUEBAS INT,
RESULTADO TEXT,
ID_OBSERVACIONTRABAJO INT,
ID_ANALISTA INT,
FECHA_BAJA DATE NOT NULL,

	FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_RESERVA) REFERENCES CEPA_RESERVA(ID_RESERVA)
);

-- tabla para cepas de trabajo 3
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO3 (
ID_TRABAJO3 INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
ID_TRABAJO2 INT,
FECHA_ACTIVACION DATE NOT NULL,
ID_PRUEBAS INT,
RESULTADO TEXT,
ID_OBSERVACIONTRABAJO INT,
ID_ANALISTA INT,
FECHA_BAJA DATE NOT NULL,

	FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_TRABAJO2) REFERENCES CEPA_TRABAJO2(ID_TRABAJO2)
);

-- tabla para cepas de trabajo 4
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO4 (
ID_TRABAJO4 INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
ID_TRABAJO3 INT,
FECHA_ACTIVACION DATE NOT NULL,
ID_PRUEBAS INT,
RESULTADO TEXT,
ID_OBSERVACIONTRABAJO INT,
ID_ANALISTA INT,
FECHA_BAJA DATE NOT NULL,

	FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_TRABAJO3) REFERENCES CEPA_TRABAJO3(ID_TRABAJO3)
);

-- tabla para cepas de trabajo 5
CREATE TABLE IF NOT EXISTS CEPA_TRABAJO5 (
ID_TRABAJO5 INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
ID_TRABAJO4 INT,
FECHA_ACTIVACION DATE NOT NULL,
ID_PRUEBAS INT,
RESULTADO TEXT,
ID_OBSERVACIONTRABAJO INT,
ID_ANALISTA INT,
FECHA_BAJA DATE NOT NULL,

	FOREIGN KEY (ID_ANALISTA) REFERENCES ANALISTA_FIRMA(ID_ANALISTA),
    FOREIGN KEY (ID_OBSERVACIONTRABAJO) REFERENCES OBSERVACION_TRABAJO(ID_OBSERVACIONTRABAJO),
    FOREIGN KEY (ID_PRUEBAS) REFERENCES PRUEBAS_CEPAS(ID_PRUEBAS),
    FOREIGN KEY (ID_TRABAJO4) REFERENCES CEPA_TRABAJO4(ID_TRABAJO4)
);