-- VISTAS
-- Vistas para STOCK DE CEPAS
CREATE OR REPLACE VIEW CEPAS_RECONSTITUIDAS AS
SELECT 
    c.NOMBRE AS CEPA,
    s.NUMERACION,
    s.FECHA_RECEPCION,
    s.FECHA_VTO,
    s.FECHA_RECONSTITUCION,
    s.RESULTADO,
    s.OBSERVACIONES,
    a.NOMBRE AS ANALISTA
FROM STOCK_CEPAS s
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
LEFT JOIN ANALISTA_FIRMA a ON s.ID_ANALISTA = a.ID_ANALISTA
WHERE s.FECHA_RECONSTITUCION IS NOT NULL;

CREATE OR REPLACE VIEW CEPAS_VENCIDAS_SIN_USAR AS
SELECT
	c.NOMBRE AS CEPA,
    s.NUMERACION,
    s.FECHA_RECEPCION,
    s.FECHA_VTO,
    s.FECHA_RECONSTITUCION,
    s.RESULTADO,
    s.OBSERVACIONES,
    a.NOMBRE AS ANALISTA
FROM STOCK_CEPAS s
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
LEFT JOIN ANALISTA_FIRMA a ON s.ID_ANALISTA = a.ID_ANALISTA
WHERE FECHA_VTO < CURDATE()
AND FECHA_RECONSTITUCION IS NULL;

CREATE OR REPLACE VIEW CEPAS_NO_VENCIDAS_SIN_USAR AS
SELECT
	c.NOMBRE AS CEPA,
    s.NUMERACION,
    s.FECHA_RECEPCION,
    s.FECHA_VTO,
    s.FECHA_RECONSTITUCION,
    s.RESULTADO,
    s.OBSERVACIONES,
    a.NOMBRE AS ANALISTA
FROM STOCK_CEPAS s
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
LEFT JOIN ANALISTA_FIRMA a ON s.ID_ANALISTA = a.ID_ANALISTA
WHERE FECHA_VTO >= CURDATE() 
AND FECHA_RECONSTITUCION IS NULL;

-- Vistas para CEPAS DE RESERVA
CREATE OR REPLACE VIEW CEPAS_RESERVA_RECONSTITUIDAS AS
SELECT
    r.NUMERO_ALICUOTA,
    r.FECHA_RECONSTITUCION,
    o.DESCRIPCION AS OBSERVACION,
    a.NOMBRE AS ANALISTA,
    c.NOMBRE AS CEPA,
    s.NUMERACION
FROM CEPA_RESERVA r
LEFT JOIN OBSERVACION_RESERVA o ON r.ID_OBSERVACION = o.ID_OBSERVACION
LEFT JOIN ANALISTA_FIRMA a ON r.ID_ANALISTA = a.ID_ANALISTA
JOIN STOCK_CEPAS s ON r.ID_STOCK = s.ID_STOCK
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
WHERE r.FECHA_RECONSTITUCION IS NOT NULL
ORDER BY c.NOMBRE, s.NUMERACION, r.NUMERO_ALICUOTA;

CREATE OR REPLACE VIEW CEPAS_RESERVA_NO_RECONSTITUIDAS AS
SELECT
    r.NUMERO_ALICUOTA,
    r.FECHA_RECONSTITUCION,
    c.NOMBRE AS CEPA,
    s.NUMERACION
FROM CEPA_RESERVA r
JOIN STOCK_CEPAS s ON r.ID_STOCK = s.ID_STOCK
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
WHERE r.FECHA_RECONSTITUCION IS NULL
ORDER BY c.NOMBRE, s.NUMERACION, r.NUMERO_ALICUOTA;

-- Vistas para CEPAS DE TRABAJO
CREATE OR REPLACE VIEW TRAZABILIDAD_CEPA_TRABAJO AS
SELECT
    c.NOMBRE AS CEPA,
    s.NUMERACION,
    r.NUMERO_ALICUOTA,
    
    -- Nivel 2
    t2.NIVEL AS NIVEL2,
    t2.FECHA_ACTIVACION AS FECHA_ACTIVACION2,
    p2.TIPOS AS PRUEBA2,
    t2.RESULTADO AS RESULTADO2,
    o2.DESCRIPCION AS OBSERVACION2,
    t2.FECHA_BAJA AS FECHA_BAJA2,
    a2.NOMBRE AS ANALISTA2,
    
    -- Nivel 3
    t3.NIVEL AS NIVEL3,
    t3.FECHA_ACTIVACION AS FECHA_ACTIVACION3,
    p3.TIPOS AS PRUEBA3,
    t3.RESULTADO AS RESULTADO3,
    o3.DESCRIPCION AS OBSERVACION3,
    t3.FECHA_BAJA AS FECHA_BAJA3,
    a3.NOMBRE AS ANALISTA3,
    
    -- Nivel 4
    t4.NIVEL AS NIVEL4,
    t4.FECHA_ACTIVACION AS FECHA_ACTIVACION4,
    p4.TIPOS AS PRUEBA4,
    t4.RESULTADO AS RESULTADO4,
    o4.DESCRIPCION AS OBSERVACION4,
    t4.FECHA_BAJA AS FECHA_BAJA4,
    a4.NOMBRE AS ANALISTA4

FROM CEPA_RESERVA r
JOIN STOCK_CEPAS s ON r.ID_STOCK = s.ID_STOCK
JOIN CEPAS c ON s.MOO_ID = c.MOO_ID
LEFT JOIN CEPA_TRABAJO t2 ON t2.ID_RESERVA_ORIGEN = r.ID_RESERVA
LEFT JOIN PRUEBAS_CEPAS p2 ON t2.ID_PRUEBAS = p2.ID_PRUEBAS
LEFT JOIN OBSERVACION_TRABAJO o2 ON t2.ID_OBSERVACIONTRABAJO = o2.ID_OBSERVACIONTRABAJO
LEFT JOIN ANALISTA_FIRMA a2 ON t2.ID_ANALISTA = a2.ID_ANALISTA
LEFT JOIN CEPA_TRABAJO t3 ON t3.ID_TRABAJO_ORIGEN = t2.ID_TRABAJO
LEFT JOIN PRUEBAS_CEPAS p3 ON t3.ID_PRUEBAS = p3.ID_PRUEBAS
LEFT JOIN OBSERVACION_TRABAJO o3 ON t3.ID_OBSERVACIONTRABAJO = o3.ID_OBSERVACIONTRABAJO
LEFT JOIN ANALISTA_FIRMA a3 ON t3.ID_ANALISTA = a3.ID_ANALISTA
LEFT JOIN CEPA_TRABAJO t4 ON t4.ID_TRABAJO_ORIGEN = t3.ID_TRABAJO
LEFT JOIN PRUEBAS_CEPAS p4 ON t4.ID_PRUEBAS = p4.ID_PRUEBAS
LEFT JOIN OBSERVACION_TRABAJO o4 ON t4.ID_OBSERVACIONTRABAJO = o4.ID_OBSERVACIONTRABAJO
LEFT JOIN ANALISTA_FIRMA a4 ON t4.ID_ANALISTA = a4.ID_ANALISTA

WHERE t2.FECHA_ACTIVACION IS NOT NULL
ORDER BY c.NOMBRE, s.NUMERACION, r.NUMERO_ALICUOTA, t2.NIVEL, t3.NIVEL, t4.NIVEL;